// Proxy API Key management
// Supports multiple keys: environment variable, auto-generated, and database-stored keys

import { randomBytes } from "crypto";
import prisma from "@/lib/prisma";
import type { ProxyKey } from "@/generated/prisma";

const ENV_PROXY_API_KEY = process.env.PROXY_API_KEY;
export const BUILTIN_PROXY_KEY_ROUTE_ID = "__builtin__";
export const BUILTIN_PROXY_KEY_DB_ID = "__builtin_proxy_key__";

let generatedKey: string | null = null;

export type BuiltInProxyKeySource = "builtin" | "env" | "auto";

export interface BuiltInProxyKeyInfo {
  id: string;
  name: string;
  key: string;
  source: BuiltInProxyKeySource;
  enabled: boolean;
  allowAllModels: boolean;
  allowedChannelIds: unknown;
  allowedModelIds: unknown;
  unifiedMode: boolean;
  allowedUnifiedModels: unknown;
  lastUsedAt: Date | null;
  usageCount: number;
  createdAt: Date | null;
  updatedAt: Date | null;
}

function createTransientBuiltInProxyKey(
  key: string,
  source: BuiltInProxyKeySource
): ProxyKey {
  const now = new Date();
  return {
    id: BUILTIN_PROXY_KEY_DB_ID,
    name:
      source === "env"
        ? "环境变量密钥"
        : source === "auto"
          ? "自动生成密钥"
          : "内置代理密钥",
    key,
    enabled: true,
    allowAllModels: true,
    allowedChannelIds: null,
    allowedModelIds: null,
    unifiedMode: true,
    allowedUnifiedModels: null,
    lastUsedAt: null,
    usageCount: 0,
    createdAt: now,
    updatedAt: now,
  };
}

/**
 * Safely parse JSON field as string array
 * Returns null if the value is not a valid string array
 */
function parseStringArray(value: unknown): string[] | null {
  if (value === null || value === undefined) {
    return null;
  }
  if (Array.isArray(value) && value.every((item) => typeof item === "string")) {
    return value as string[];
  }
  // Log warning for invalid data
  return null;
}

/**
 * Generate a random API key in sk-xxx format
 */
export function generateApiKey(): string {
  const randomPart = randomBytes(32)
    .toString("base64")
    .replace(/[+/=]/g, "")
    .substring(0, 48);
  return `sk-${randomPart}`;
}

/**
 * Get the proxy API key (legacy - returns env or auto-generated key)
 * - If PROXY_API_KEY env is set, use it
 * - Otherwise, auto-generate one (persists for process lifetime)
 */
export function getProxyApiKey(): string {
  if (ENV_PROXY_API_KEY) {
    return ENV_PROXY_API_KEY;
  }

  if (!generatedKey) {
    generatedKey = generateApiKey();
  }

  return generatedKey;
}

/**
 * Check if the key was auto-generated or from environment
 */
export function isKeyFromEnvironment(): boolean {
  return !!ENV_PROXY_API_KEY;
}

export async function getBuiltInProxyKeyRecord(): Promise<ProxyKey | null> {
  try {
    return await prisma.proxyKey.findUnique({
      where: { id: BUILTIN_PROXY_KEY_DB_ID },
    });
  } catch {
    return null;
  }
}

export async function getBuiltInProxyKeyInfo(): Promise<BuiltInProxyKeyInfo> {
  const builtInRecord = await getBuiltInProxyKeyRecord();
  if (builtInRecord) {
    return {
      id: BUILTIN_PROXY_KEY_ROUTE_ID,
      name: builtInRecord.name || "内置代理密钥",
      key: builtInRecord.key,
      source: "builtin",
      enabled: builtInRecord.enabled,
      allowAllModels: builtInRecord.allowAllModels,
      allowedChannelIds: builtInRecord.allowedChannelIds,
      allowedModelIds: builtInRecord.allowedModelIds,
      unifiedMode: builtInRecord.unifiedMode,
      allowedUnifiedModels: builtInRecord.allowedUnifiedModels,
      lastUsedAt: builtInRecord.lastUsedAt,
      usageCount: builtInRecord.usageCount,
      createdAt: builtInRecord.createdAt,
      updatedAt: builtInRecord.updatedAt,
    };
  }

  if (ENV_PROXY_API_KEY) {
    return {
      id: BUILTIN_PROXY_KEY_ROUTE_ID,
      name: "环境变量密钥",
      key: ENV_PROXY_API_KEY,
      source: "env",
      enabled: true,
      allowAllModels: true,
      allowedChannelIds: null,
      allowedModelIds: null,
      unifiedMode: true,
      allowedUnifiedModels: null,
      lastUsedAt: null,
      usageCount: 0,
      createdAt: null,
      updatedAt: null,
    };
  }

  return {
    id: BUILTIN_PROXY_KEY_ROUTE_ID,
    name: "自动生成密钥",
    key: getProxyApiKey(),
    source: "auto",
    enabled: true,
    allowAllModels: true,
    allowedChannelIds: null,
    allowedModelIds: null,
    unifiedMode: true,
    allowedUnifiedModels: null,
    lastUsedAt: null,
    usageCount: 0,
    createdAt: null,
    updatedAt: null,
  };
}

/**
 * Validate API key result
 */
export interface ValidateKeyResult {
  valid: boolean;
  keyRecord?: ProxyKey;
  isEnvKey?: boolean;
  isAutoGenerated?: boolean;
}

/**
 * Validate a proxy API key
 * Priority: Environment variable > Database keys > Auto-generated key
 */
export async function validateProxyKey(apiKey: string): Promise<ValidateKeyResult> {
  const builtInRecord = await getBuiltInProxyKeyRecord();
  if (builtInRecord && apiKey === builtInRecord.key) {
    if (!builtInRecord.enabled) {
      return { valid: false };
    }

    prisma.proxyKey.update({
      where: { id: builtInRecord.id },
      data: {
        lastUsedAt: new Date(),
        usageCount: { increment: 1 },
      },
    }).catch(() => {
    });

    return { valid: true, keyRecord: builtInRecord };
  }

  if (!builtInRecord) {
    const builtInKey = await getBuiltInProxyKeyInfo();
    if (apiKey === builtInKey.key) {
      return {
        valid: true,
        keyRecord: createTransientBuiltInProxyKey(builtInKey.key, builtInKey.source),
      };
    }
  }

  try {
    const keyRecord = await prisma.proxyKey.findUnique({
      where: { key: apiKey },
    });

    if (keyRecord) {
      if (!keyRecord.enabled) {
        return { valid: false };
      }

      prisma.proxyKey.update({
        where: { id: keyRecord.id },
        data: {
          lastUsedAt: new Date(),
          usageCount: { increment: 1 },
        },
      }).catch(() => {
      });

      return { valid: true, keyRecord };
    }
  } catch {
  }

  if (!ENV_PROXY_API_KEY) {
    const autoKey = getProxyApiKey();
    if (apiKey === autoKey) {
      return { valid: true, isAutoGenerated: true };
    }
  }

  return { valid: false };
}

/**
 * Check if a key has permission to access a specific model
 * @param keyRecord - The proxy key record (undefined for env/auto-generated keys)
 * @param isEnvKey - Whether the key is from environment variable
 * @param channelId - The channel ID
 * @param modelId - The model ID
 * @param modelStatus - The model's last test status (true = healthy, false = unhealthy, null = untested)
 */
export async function canAccessModel(
  keyRecord: ProxyKey | undefined,
  isEnvKey: boolean | undefined,
  channelId: string,
  modelId: string,
  modelStatus: boolean | null,
  modelName?: string
): Promise<boolean> {
  // Environment key and auto-generated key have full access
  if (isEnvKey) {
    return true;
  }

  // No key record means auto-generated key (full access)
  if (!keyRecord) {
    return true;
  }

  // If key allows all models, check model status
  if (keyRecord.allowAllModels) {
    // Only explicitly healthy models can be accessed.
    return modelStatus === true;
  }

  // allowAllModels=false: only explicitly specified channels/models are allowed
  // 统一模式优先用 allowedUnifiedModels 检查裸模型名
  if (keyRecord.unifiedMode && modelName) {
    const allowedUnified = parseStringArray(keyRecord.allowedUnifiedModels);
    if (allowedUnified && allowedUnified.length > 0) {
      return allowedUnified.includes(modelName);
    }
  }

  // Permission logic: channel match OR model match grants access
  const allowedChannelIds = parseStringArray(keyRecord.allowedChannelIds);
  const allowedModelIds = parseStringArray(keyRecord.allowedModelIds);

  // If no explicit permissions configured, deny all
  const hasChannelPerms = allowedChannelIds !== null && allowedChannelIds.length > 0;
  const hasModelPerms = allowedModelIds !== null && allowedModelIds.length > 0;

  if (!hasChannelPerms && !hasModelPerms) {
    return false;
  }

  // Grant access if channel OR model is in the allowed list
  if (hasChannelPerms && allowedChannelIds.includes(channelId)) {
    return true;
  }
  if (hasModelPerms && allowedModelIds.includes(modelId)) {
    return true;
  }

  return false;
}

/**
 * Mask key for display (show only first 8 and last 4 chars)
 */
export function maskKey(key: string): string {
  if (key.length <= 12) {
    return key.substring(0, 4) + "****";
  }
  return key.substring(0, 8) + "..." + key.substring(key.length - 4);
}

export async function getAccessibleModels(keyRecord: ProxyKey | undefined, isEnvKey: boolean | undefined): Promise<{
  allModels: boolean;
  channelIds?: string[];
  modelIds?: string[];
}> {
  // Environment key and auto-generated key have full access
  if (isEnvKey || !keyRecord) {
    return { allModels: true };
  }

  if (keyRecord.allowAllModels) {
    return { allModels: true };
  }

  return {
    allModels: false,
    channelIds: parseStringArray(keyRecord.allowedChannelIds) ?? undefined,
    modelIds: parseStringArray(keyRecord.allowedModelIds) ?? undefined,
  };
}
